### PR TITLE
fix!: allow rendering of numeric values

### LINKED ISSUE #131: [Bug]: Int caputres are resent as strings / YAML parsing capabilities
### What happened?

I am capturing a number from json response. Capture value is an integer primitive,
in the next step I am sending the value using template but it fails (my service is strict about types) because integer capture is converted back to string.

### What did you expect to happen?

Integer captures should be sent as integers, not strings.
Alternatively templating engine should provide functions for converting strings to numbers.
If nothing from above is possible, YAML parsing should allow for explicit types definition like this: https://www.educative.io/answers/how-to-represent-different-basic-data-types-in-yaml

### Version

2.6.6

### Environment

Node v18.12.1

### How can we reproduce this bug?

workflow file:
```yaml
name: ABC
env:
  host: localhost:4000
tests:
  describe_toy:
    steps:
      - name: Get next toy
        http:
          url: http://${{env.host}}/api/toys/new
          method: POST
          headers:
            Content-Type: application/json
          captures:
            toy_id:
              jsonpath: $.toy_id
          check:
            status: 200
            jsonpath:
              $.toy_id:
                - isNumber: true
              $.text:
                - isString: true

      - name: Generate upload URL
        http:
          url: http://${{env.host}}/api/toys
          method: POST
          headers:
            Content-Type: application/json
          json:
            toy_id: ${{ captures.toy_id }}
          check:
            status: 201

```

First step passes all the checks including:
- toy_id is number

Next step fails:
```yaml
          json:
            toy_id: ${{ captures.toy_id }}
```
because this capture sends string representation of a number e.g.:`"100"`, I expect simple number `100`.

Is there a way to force this behavior or this counts as a bug?

### Relevant log output

_No response_

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me

### PR DESCRIPTION
**Pull request by alenaksu**
This PR makes it possible to render numeric values from strings that contain just one expression, which was not possible before as any expression was converted to a string.

It also introduces unit tests, as they were totally missing. This should make the codebase more robust.

Should fix https://github.com/stepci/stepci/issues/131

### CODE REVIEW

**Comment by mishushakov** [comment]
Yo Alessandro, thanks a lot for your work? Could I ask for one more thing please?

Could you add a .prettierrc file that looks like this and format the code accordingly?

```json
{
  "singleQuote": true,
  "semi": false
}
```

Have you also tested with the examples from the docs?

**Comment by alenaksu** [comment]
> Have you also tested with the examples from the docs?

You mean in the ones in the README?

**Comment by mishushakov** [comment]
Here:
https://docs.stepci.com/reference/templating.html

**Comment by alenaksu** [comment]
>Here:
https://docs.stepci.com/reference/templating.html

If you're asking whether I tested the integration with StepCI, the answer is no. I've solely tested the library itself. However, the unit tests should cover all of these cases.

**Comment by mishushakov** [comment]
Fair enough! I will review in the next few days and looking forward to get it merged 😉

**Comment by mishushakov** [comment]
Looks good to me for now. Thanks for your contribution 🙏

**Pull request merged**
